### ISSUE TITLE
Generating using only Remote Server

### ISSUE THREAD

**Issue by Beamhi** [city96/ComfyUI_NetDist#12]
Is there a way to generate using only the remote server?

**Comment by Beamhi** [comment]
figured it out

**Comment by MaxTretikov** [comment]
@Beamhi What did you do?

**Comment by nux1111** [comment]
@MaxTretikov sorry for taking so long to respond. I was new to github when I made that issue and didn't see your comments; and apparently, I didn't have a solution for that then but when I attempted to solve the issue last week, I saw your comment and decided when I fix it, I will message you first. https://github.com/nux1111/ComfyUI_NetDist_Plus
