### ISSUE TITLE
Queue on remote ERROR: Error occurred when executing RemoteQueueSimple:  Out of range float values are not JSON compliant EDIT: Happens on ALL Queue on remote node

### ISSUE THREAD

**Issue by Aunxfb** [city96/ComfyUI_NetDist#14]
![image](https://github.com/city96/ComfyUI_NetDist/assets/13115169/b496e86d-7d08-4e5d-9612-3d06614a4807)
![image](https://github.com/city96/ComfyUI_NetDist/assets/13115169/d338918f-6278-41c2-874a-5569299bb129)

Not sure what I'm doing wrong here? 

ComfyUI: 1927\[05cd00\](2024-01-23)
Manager: V1.17.1

**Comment by city96** [comment]
I've had someone mention this before but I was never able to reproduce it. Could you share the workflow that causes it?

**Comment by Aunxfb** [comment]
[workflow.json](https://github.com/city96/ComfyUI_NetDist/files/14293492/workflow.json)

Here it is.

**Comment by city96** [comment]
Thanks. I think I figured out what the issue was and pushed a fix. Can you test it out?

**Comment by Aunxfb** [comment]
Works now, thanks & kudos for your swift action @city96 !!!
