### ISSUE TITLE
Can I use this to load balance runs?

### ISSUE THREAD

**Issue by ckao10301** [city96/ComfyUI_NetDist#28]
Hi, is it possible to use this to load balance? For example, I have 4 gpus with 4 comfy instances. If I execute 4 runs, each run goes to a separate comfy instance. If the queue is higher than 4, then each run gets allocated depending on the availability of the gpu. 

Use case: trying to set up my local server to process comfy api requests.

**Comment by city96** [comment]
Not in it's current form I don't think, though I haven't messed with this repo in a long time.

If you're only routing API requests then you could probably have a small python script that checks the availability of each instance, then sends it to the one with the least requests in the queue. Not sure how you'd handle any of the websocket endpoints, though I guess that depends on if you're using them in the first place or not.

**Comment by ckao10301** [comment]
I found cloudflare load balancer, which should meet my needs.
