### ISSUE TITLE
How to combine multiple cards to solve the problem of insufficient memory in comfyui

### ISSUE THREAD

**Issue by Nuclear6** [city96/ComfyUI_NetDist#31]
Hi, this is a great project! It seems that a distributed approach is used to solve the problem of combined use of multiple cards. Each card runs a comfyui instance. However, the problem I encountered is that I only want to run one comfyui instance and combine four A10 cards as one A800 card. Is there any solution to this case? Or is it impossible to do it based on the principles of comfyui?

**Comment by north151** [comment]
Have you solved this problem? I have the same problem?

**Comment by Nuclear6** [comment]
There is no such solution. Finally, the problem was solved by changing to an A800 machine with 80G VRAM.
