### ISSUE TITLE
Noob question how to run this on local pc

### ISSUE THREAD

**Issue by dfghsderftgerdf** [city96/ComfyUI_NetDist#4]
I have a some A4000's I want to run on stable diffusion, I've looked over you documentation and still a bit confused on how I would set this up. Can you break it down step by step please. Also would it be possible to use multiple gpu's simultaneously? I'm trying to run some animation using AnimateDiff received an error saying I needed 24gb's of memory. Which I do have I just need a way to run more than one gpu at the same time. Any options would be great thanks.

**Comment by city96** [comment]
Hi! I haven't tested it with animatediff so I can't tell if it'd work.

Though even if it does, you won't actually combine the VRAM of your two cards, you'll just be generating two separate animations (one on each card) so this repo probably isn't what you need if you're limited by VRAM amount.

There's some usage info in Issue #2 but IMO you should try out the standalone [animatediff cli](https://github.com/neggles/animatediff-cli) repo for lower VRAM usage.

Alternatively, try to gen your base animation at a lower res and then upscale each frame (you don't have to combine them into a gif in one step. At least in [animatediff evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved) they just act like a batch of latents you can split apart->upscale individually->recombine and *then* combine them into a gif)

**Comment by dfghsderftgerdf** [comment]
Bro you just saved me loads of time lmao. Thanks a bunch this is what I was missing didn't know that was even possible.

**Comment by city96** [comment]
No problem lol, always happy to help.
