### ISSUE TITLE
I'm new. Can we  generate a images by using 2 GPUs at once ? As a comfyUI's default workflow by use case? Thank you

### ISSUE THREAD

**Issue by Erwin11** [city96/ComfyUI_NetDist#9]
I'm new. I'm curious. 
Can we  generate a images by using 2 GPUs at once ? As a comfyUI's default workflow by use case? Thank you

Or it is use for generate  batch images?  
like generate  4 images at once, we can use multi gpu to separate tasks to each GPU and do it ？ It seems like that .

**Comment by city96** [comment]
This repo can only do batch processing, so with two GPUs you will get two output images. As you say, with 4 GPUs you can split them - 2 on each GPU, 3 on the first 1 on the second, etc. You can also change the batches, doing multiple images on the same GPU.

I want to try and make it so two GPUs can work on the same image via tiled sampling, but that is currently not implemented.

**Comment by Erwin11** [comment]
I get it. Thanks for your hard work!
